# Generated by Django 4.0.2 on 2022-04-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_application_company_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
