# Generated by Django 4.0.3 on 2022-03-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mymodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('College', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Year', models.CharField(max_length=30)),
                ('Age', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('JobsApplied', models.CharField(max_length=30)),
                ('Interviews', models.CharField(max_length=30)),
                ('Joboffers', models.CharField(max_length=30)),
                ('img', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
