# Generated by Django 4.0.2 on 2022-05-18 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_year',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
