# Generated by Django 4.0.2 on 2022-04-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_label_label_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
